### ISSUE TITLE
ModuleNotFoundError: No module named 'countdown'

### ISSUE THREAD

**Issue by vip0411** [VAIBHAVPATEL97/Crypto-Price-Prediction-System#1]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-2ce6810e2e97>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from countdown import countdown
      2 import pandas as pd
      3 import datetime
      4 import os, requests
      5 import uuid

ModuleNotFoundError: No module named 'countdown'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
![Screenshot (35)](https://github.com/VAIBHAVPATEL97/Crypto-Price-Prediction-System/assets/96435601/d9c786cc-fa52-43ed-81e6-95468a1fe104)

**Comment by VAIBHAVPATEL97** [comment]
Hi @vip0411,
Please use `!pip install -r requirements.txt` command in the google colab environment to install package dependencies. Cheers!
